baseurl = "https://salicorne.github.io/"
languageCode = "fr-fr"
title = "Salicorne.dev"
theme = "hugo-cards"
themesDir = "themes"
paginate = 6

[params]
  #builtBy = "bool"
  defaultImage = "todd.png" # static/images

  facebook = ""
  quora = ""
  twitter = ""
  github = "https://github.com/Salicorne"
  instagram = "https://instagram.com/lesalicorne"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

#[params.copyright]
#  name = "bool"
#  link = "https://bool.netlify.com"

